# Generated by Django 4.2.1 on 2024-08-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_date_of_join_patient_pov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sub',
            field=models.CharField(max_length=1000),
        ),
    ]
