# Generated by Django 4.2.1 on 2024-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pov',
        ),
        migrations.AddField(
            model_name='patient',
            name='stat',
            field=models.BinaryField(default=False),
        ),
    ]
